version: '3.1'
services:
#  mysql:
#    image: mysql
#    restart: always
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: mydearkid
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydearkid
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "D:/ddata:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8999:8080"
  # server:
  #   image: clssw1004/mydearkid:0.1
  #   restart: always
  #   ports:
  #     - "18081:17777"
  #   volumes:
  #     - F:/cuiwei/Images:/media/photos
  #     - D:/thumbnail:/media/thumbnail
  #   environment:
  #     DRIVER_CLASS_NAME: org.postgresql.Driver
  #     JDBC_URL: jdbc:postgresql://postgres:5432/mydearkid
  #     DB_USER: postgres
  #     DB_PASSWORD: 123456
  #     THUMBNAIL_PATH: /media/photos
  #     PHOTO_PATH: /media/thumbnail
