server:
  port: ${SERVER_PORT:17777}
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${JDBC_URL:jdbc:postgresql://192.168.2.235:5432/mydearkid}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
config:
  path:
    photo: ${PHOTO_PATH:D:/cuiwei/Images}
    thumbnail: ${THUMBNAIL_PATH:D:/thumbnail}
  extensions: ${EXTENSIONS:jpeg,png,bmp,jpg}
