server:
  port: ${SERVER_PORT:17777}
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${JDBC_URL:jdbc:postgresql://127.0.0.1:5432/mydearkid}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
config:
  path:
    photo: ${PHOTO_PATH:/home/cuiwei/warhouse/images}
    thumbnail: ${THUMBNAIL_PATH:/home/cuiwei/warhouse/thumbnail}