// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElRow: typeof import('element-plus/es')['ElRow']
    GalleryWall: typeof import('./src/components/GalleryWall.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Photo: typeof import('./src/components/Photo.vue')['default']
    PhotoItem: typeof import('./src/components/PhotoItem.vue')['default']
  }
}
